num1 = int(input("enter a number: "))
num2 = int(input("enter another number: "))
print("Addition:",num1+num2)
print("Subtraction:",num1-num2)
print("Multiplication:",num1*num2)
print("Division:",num1/num2)
